# -*- coding: utf-8 -*-
"""churn_analysis_model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CA9AvVFS38BxkjMhyxCk0rA9n67IxfsR
"""

!pip install boto3 -q
!pip install xgboost -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN
import boto3
from google.colab import userdata
import os
from io import BytesIO
from sklearn.ensemble import RandomForestClassifier
import sys
sys.path.append("/content/sample_data")
from lib.read_file_model import read_from_s3
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV

try:
    aws_access_key = userdata.get('AWS_ACCESS_KEY_ID').strip()
    aws_secret_key = userdata.get('AWS_SECRET_ACCESS_KEY').strip()
    print("AWS Credentials loaded from Colab Secrets")
except:
    print("Please add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in Colab Secrets first!")
    raise

os.environ['AWS_ACCESS_KEY_ID'] = aws_access_key
os.environ['AWS_SECRET_ACCESS_KEY'] = aws_secret_key
print("AWS credentials loaded successfully")

AWS_REGION = 'us-east-1'
s3 = boto3.client('s3',region_name = AWS_REGION)

# read from s3

found_key = None
response = s3.list_objects_v2(Bucket="ibm-internship-major-staging", Prefix="ibm_internship_major/staging/")
if 'Contents' in response:
    print("Files found inside the folder:\n")
    latest_date = response['Contents'][0]['LastModified']
    for obj in response['Contents']:
        latest_date = max(latest_date,obj['LastModified'])
        if latest_date == obj['LastModified']:
          found_key = obj["Key"]

else:
    print("No files found in this folder.")

if found_key != None:
  data = read_from_s3(
      bucket_name="ibm-internship-major-staging",
      s3_key= found_key
  )

x = data.drop('Churn',axis=1)
x

y = data['Churn']

y.value_counts()

"""# Decision Tree"""

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
model_dt = DecisionTreeClassifier(criterion='gini',random_state=100,max_depth=6,min_samples_leaf=8)
model_dt.fit(x_train,y_train)
y_pred = model_dt.predict(x_test)
model_dt.score(x_test,y_test)
print(classification_report(y_test, y_pred, labels=[0,1]))

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

model_dt.fit(x_train,y_train)

y_pred=model_dt.predict(x_test)
y_pred

model_dt.score(x_test,y_test)

print(classification_report(y_test, y_pred, labels=[0,1]))

"""As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datasets.
Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.
"""

sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(metrics.classification_report(yr_test, yr_predict))

print(metrics.confusion_matrix(yr_test, yr_predict))



model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

model_rf.fit(x_train,y_train)

y_pred=model_rf.predict(x_test)

model_rf.score(x_test,y_test)

print(classification_report(y_test, y_pred, labels=[0,1]))

sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

model_rf_smote.fit(xr_train1,yr_train1)

yr_predict1 = model_rf_smote.predict(xr_test1)

model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

print(model_score_r1)
print(metrics.classification_report(yr_test1, yr_predict1))

print(metrics.confusion_matrix(yr_test1, yr_predict1))

from sklearn.decomposition import PCA
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)
model.fit(xr_train_pca,yr_train1)
yr_predict_pca = model.predict(xr_test_pca)
model_score_r_pca = model.score(xr_test_pca, yr_test1)
print(model_score_r_pca)
print(metrics.classification_report(yr_test1, yr_predict_pca))

model_nb = GaussianNB()
model_nb.fit(xr_train1, yr_train1)

yr_pred_nb = model_nb.predict(xr_test1)

print("Naive Bayes Accuracy:", model_nb.score(xr_test1, yr_test1))
print(metrics.classification_report(yr_test1, yr_pred_nb))
print(metrics.confusion_matrix(yr_test1, yr_pred_nb))

model_lr = LogisticRegression(max_iter=1000, random_state=100)
model_lr.fit(xr_train1, yr_train1)

yr_pred_lr = model_lr.predict(xr_test1)

print("Logistic Regression Accuracy:", model_lr.score(xr_test1, yr_test1))
print(metrics.classification_report(yr_test1, yr_pred_lr))
print(metrics.confusion_matrix(yr_test1, yr_pred_lr))

model_xgb = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=100,
    eval_metric='logloss'
)

model_xgb.fit(xr_train1, yr_train1)

yr_pred_xgb = model_xgb.predict(xr_test1)

print("XGBoost Accuracy:", model_xgb.score(xr_test1, yr_test1))
print(metrics.classification_report(yr_test1, yr_pred_xgb))
print(metrics.confusion_matrix(yr_test1, yr_pred_xgb))

param_rf = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [4, 6, 8, 10, 12, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4, 8],
    'max_features': ['sqrt', 'log2', None]
}

rf_random = RandomizedSearchCV(
    estimator=RandomForestClassifier(random_state=100),
    param_distributions=param_rf,
    n_iter=30,
    cv=3,
    scoring='f1',
    n_jobs=-1,
    verbose=1,
    random_state=100
)

rf_random.fit(xr_train1, yr_train1)
print("Best RF Parameters:", rf_random.best_params_)
print("Best RF Score:", rf_random.best_score_)

best_rf = rf_random.best_estimator_
print(classification_report(yr_test1, best_rf.predict(xr_test1)))

param_xgb = {
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [3, 4, 5, 6, 8],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2],
    'min_child_weight': [1, 3, 5]
}

xgb_random = RandomizedSearchCV(
    estimator=XGBClassifier(random_state=100, eval_metric='logloss'),
    param_distributions=param_xgb,
    n_iter=40,
    cv=3,
    scoring='f1',
    n_jobs=-1,
    verbose=1,
    random_state=100
)

xgb_random.fit(xr_train1, yr_train1)

print("Best XGBoost Parameters:", xgb_random.best_params_)
print("Best XGBoost Score:", xgb_random.best_score_)

best_xgb = xgb_random.best_estimator_
print(classification_report(yr_test1, best_xgb.predict(xr_test1)))

import pickle

# Save all models
pickle.dump(model_rf_smote, open('model_rf_smote.sav', 'wb'))
pickle.dump(model_nb, open('model_nb.sav', 'wb'))
pickle.dump(model_lr, open('model_lr.sav', 'wb'))
pickle.dump(model_xgb, open('model_xgb.sav', 'wb'))
pickle.dump(best_rf, open('best_rf.sav', 'wb'))
pickle.dump(best_xgb, open('best_xgb.sav', 'wb'))

print("All models saved successfully!")

load_model = pickle.load(open('model_xgb.sav', 'rb'))
print("XGBoost loaded successfully. Score:", load_model.score(xr_test1, yr_test1))

"""Our final model i.e. RF Classifier with SMOTEENN, is now ready and dumped in model.sav, which we will use and prepare API's so that we can access our model from UI."""

# !pip install boto3 -q
# import boto3
# import pandas as pd
# from io import BytesIO
# AWS_REGION = 'us-east-1'

# def read_from_s3(bucket_name, s3_key):
#     try:
#         s3 = boto3.client('s3',region_name = AWS_REGION)
#         response = s3.get_object(Bucket=bucket_name, Key=s3_key)
#         print("File Found")
#         file_content = response['Body'].read()

#         if s3_key.lower().endswith('.xlsx'):
#             df = pd.read_excel(BytesIO(file_content))

#         elif s3_key.lower().endswith('.csv'):
#             df = pd.read_csv(BytesIO(file_content))
#         else:
#             df = pd.read_excel(BytesIO(file_content))  # default

#         print(f"Successfully loaded: s3://{bucket_name}/{s3_key}")
#         print(f"Shape: {df.shape}")
#         return df

#     except Exception as e:
#         print(f"Error: {e}")
#         return None

