# -*- coding: utf-8 -*-
"""churn_analysis_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFg1ZRZYSsApCcUzKMVjEAg3DAkYCRU0
"""

!pip install boto3 -q

import boto3
from botocore.exceptions import ClientError
from google.colab import userdata
import os

try:
    aws_access_key = userdata.get('AWS_ACCESS_KEY_ID').strip()
    aws_secret_key = userdata.get('AWS_SECRET_ACCESS_KEY').strip()
    print("AWS Credentials loaded from Colab Secrets")
except:
    print("Please add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in Colab Secrets first!")
    raise

os.environ['AWS_ACCESS_KEY_ID'] = aws_access_key
os.environ['AWS_SECRET_ACCESS_KEY'] = aws_secret_key
print("AWS credentials loaded successfully")

AWS_REGION = "us-east-1"

BUCKET_PREFIX = "ibm-internship-major"

SOURCE_BUCKET = f"{BUCKET_PREFIX}-source"
STAGING_BUCKET = f"{BUCKET_PREFIX}-staging"
DESTINATION_BUCKET = f"{BUCKET_PREFIX}-destination"


s3 = boto3.client('s3', region_name=AWS_REGION)

def create_bucket(bucket_name):
    try:
        if AWS_REGION == "us-east-1":
            s3.create_bucket(Bucket=bucket_name)
        else:
            s3.create_bucket(
                Bucket=bucket_name,
                CreateBucketConfiguration={'LocationConstraint': AWS_REGION}
            )
        print(f"Created: {bucket_name}")
    except ClientError as e:
        if e.response['Error']['Code'] == 'BucketAlreadyOwnedByYou':
            print(f"Bucket already exists: {bucket_name}")
        else:
            print(f" Error creating {bucket_name}: {e}")


print("Creating AWS S3 Data Lake...\n")

create_bucket(SOURCE_BUCKET)
create_bucket(STAGING_BUCKET)
create_bucket(DESTINATION_BUCKET)


def create_folder(bucket, folder):
    try:
        s3.put_object(Bucket=bucket, Key=folder)
        print(f"Folder created: s3://{bucket}/{folder}")
    except:
        pass

print("\nCreating folder structure...")


create_folder(SOURCE_BUCKET, "ibm_internship_major/source/")
create_folder(SOURCE_BUCKET, "ibm_internship_major/source/raw/")


create_folder(STAGING_BUCKET, "ibm_internship_major/staging/")


create_folder(DESTINATION_BUCKET, "ibm_internship_major/destination/")

print("\n AWS S3 Data Lake Setup Completed!")
print(f"Source Bucket     : {SOURCE_BUCKET}")
print(f"Staging Bucket    : {STAGING_BUCKET}")
print(f"Destination Bucket: {DESTINATION_BUCKET}")

import requests
from io import BytesIO
from urllib.parse import urlparse
from datetime import datetime

GITHUB_REPO = "https://github.com/aritra-iitkgp/IBM_Internship_Major"
BRANCH = "dev"

timestamp = datetime.now()
print(type(timestamp))
time_stamp=timestamp.strftime("%d-%m-%Y %H:%M")
print(time_stamp)

S3_SOURCE_BUCKET = "ibm-internship-major-source"

S3_PREFIX = f"ibm_internship_major/source/raw/{time_stamp}/"




def download_from_github(repo_url, branch="dev"):

    if "github.com" in repo_url:
        repo_url = repo_url.replace("github.com", "raw.githubusercontent.com")
        repo_url = f"{repo_url}/{branch}"

    print(f"Fetching files from: {repo_url}")


    files_to_download = [
        "Files/Telco-Customer-Churn.csv"

    ]

    uploaded_files = []

    for file_path in files_to_download:
        raw_url = f"{repo_url}/{file_path}"
        print(f"Downloading: {raw_url}")

        response = requests.get(raw_url)
        print(f"Status Code: {response.status_code}")
        if response.status_code == 200:
            file_name = os.path.basename(file_path)
            s3_key = S3_PREFIX + file_name


            s3.upload_fileobj(BytesIO(response.content), S3_SOURCE_BUCKET, s3_key)

            print(f"Uploaded: {file_name} → s3://{S3_SOURCE_BUCKET}/{s3_key}")
            uploaded_files.append(file_name)
        else:
            print(f"Failed to download: {file_path}")

    return uploaded_files


uploaded = download_from_github(GITHUB_REPO, BRANCH)
print(f"\n Successfully uploaded {len(uploaded)} files to S3 Source Bucket!")

!pip install boto3 -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
def read_from_s3(bucket_name, s3_key):
    try:
        response = s3.get_object(Bucket=bucket_name, Key=s3_key)
        print("File Found")
        file_content = response['Body'].read()

        if s3_key.lower().endswith('.xlsx'):
            df = pd.read_excel(BytesIO(file_content))

        elif s3_key.lower().endswith('.csv'):
            df = pd.read_csv(BytesIO(file_content))
        else:
            df = pd.read_excel(BytesIO(file_content))  # default

        print(f"Successfully loaded: s3://{bucket_name}/{s3_key}")
        print(f"Shape: {df.shape}")
        return df

    except Exception as e:
        print(f"Error: {e}")
        return None
found_key = None
response = s3.list_objects_v2(Bucket="ibm-internship-major-source", Prefix=f"ibm_internship_major/source/raw/{time_stamp}/")
if 'Contents' in response:
    print("Files found inside the folder:\n")
    for obj in response['Contents']:
        print(obj['Key'])
        if "Telco-Customer-Churn.csv" in obj['Key']:
          found_key = obj['Key']
          print(f"\n Found your file: {obj['Key']}")
          break
else:
    print("No files found in this folder.")

if found_key != None:
  sheets = read_from_s3(
      bucket_name="ibm-internship-major-source",
      s3_key= found_key
  )

# Show first few rows

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.ticker as mtick
import matplotlib.pyplot as plt
# %matplotlib inline

telco_base_data = sheets
telco_base_data.head()

telco_base_data.shape

telco_base_data.columns.values

"""SeniorCitizen is actually a categorical hence the 25%-50%-75% distribution is not propoer

75% customers have tenure less than 55 months

Average Monthly charges are USD 64.76 whereas 25% customers pay more than USD 89.85 per month
"""

telco_base_data.describe()

telco_base_data.info()

telco_base_data['Churn'].value_counts().plot(kind = 'bar',figsize=(8,6))
plt.xlabel("Count", labelpad=12)
plt.ylabel("Target Variable", labelpad=12)
plt.title("Count of TARGET Variable per category", y=1.02)

100*telco_base_data['Churn'].value_counts()/len(telco_base_data['Churn'])

telco_base_data['Churn'].value_counts()

"""Data is highly imbalanced, ratio = 73:27
So we analyse the data with other features while taking the target values separately to get some insights.
"""

telco_base_data.shape[0]

missing = pd.DataFrame((telco_base_data.isnull().sum())*100/telco_base_data.shape[0]).reset_index()
missing

missing = pd.DataFrame((telco_base_data.isnull().sum()) * 100 / telco_base_data.shape[0]).reset_index()
missing.columns = ['column', 'percentage']
plt.figure(figsize=(16,5))
ax = sns.pointplot(data=missing, x='column', y='percentage')
plt.xticks(rotation=90, fontsize=7)
plt.title("Percentage of Missing values")
plt.ylabel("PERCENTAGE")
plt.show()

"""Missing Data - Initial Intuition
Here, we don't have any missing data.
"""

telco_data = telco_base_data.copy()

telco_data.TotalCharges = pd.to_numeric(telco_data.TotalCharges, errors='coerce')
telco_data.isnull().sum()

telco_data[telco_data['TotalCharges'].isnull() == True]

"""4. Missing Value Treatement

Since the % of these records compared to total dataset is very low ie 0.15%, it is safe to ignore them from further processing.
"""

telco_data.dropna(how='any',inplace=True)

"""5. Divide customers into bins based on tenure e.g. for tenure < 12 months: assign a tenure group if 1-12, for tenure between 1 to 2 Yrs, tenure group of 13-24; so on..."""

print(telco_data['tenure'].max())

labels = ["{0} - {1}".format(i, i + 11) for i in range(1, 72, 12)]

telco_data['tenure_group'] = pd.cut(telco_data.tenure, range(1, 80, 12), right=False, labels=labels)

telco_data['tenure_group'].value_counts()

telco_data.drop(columns= ['customerID','tenure'], axis=1, inplace=True)
telco_data.head()

"""1. ** Plot distibution of individual predictors by churn

Univariate Analysis
"""

for i, predictor in enumerate(telco_data.drop(columns=['Churn', 'TotalCharges', 'MonthlyCharges'])):
    plt.figure(i)
    sns.countplot(data=telco_data, x=predictor, hue='Churn')

telco_data['Churn'] = np.where(telco_data.Churn == 'Yes',1,0)

telco_data.head()

telco_data_dummies = pd.get_dummies(telco_data)
telco_data_dummies.head()

sns.lmplot(data=telco_data_dummies, x='MonthlyCharges', y='TotalCharges', fit_reg=False)

"""Total Charges increase as Monthly Charges increase - as expected.

**10. ** Churn by Monthly Charges and Total Charges
"""

Mth = sns.kdeplot(telco_data_dummies.MonthlyCharges[(telco_data_dummies["Churn"] == 0) ],
                color="Red", shade = True)
Mth = sns.kdeplot(telco_data_dummies.MonthlyCharges[(telco_data_dummies["Churn"] == 1) ],
                ax =Mth, color="Blue", shade= True)
Mth.legend(["No Churn","Churn"],loc='upper right')
Mth.set_ylabel('Density')
Mth.set_xlabel('Monthly Charges')
Mth.set_title('Monthly charges by churn')

"""Insight: Churn is high when Monthly Charges ar high"""

Tot = sns.kdeplot(telco_data_dummies.TotalCharges[(telco_data_dummies["Churn"] == 0) ],
                color="Red", shade = True)
Tot = sns.kdeplot(telco_data_dummies.TotalCharges[(telco_data_dummies["Churn"] == 1) ],
                ax =Tot, color="Blue", shade= True)
Tot.legend(["No Churn","Churn"],loc='upper right')
Tot.set_ylabel('Density')
Tot.set_xlabel('Total Charges')
Tot.set_title('Total charges by churn')

"""*Surprising insight ** as higher Churn at lower Total Charges

However if we combine the insights of 3 parameters i.e. Tenure, Monthly Charges & Total Charges then the picture is bit clear :- Higher Monthly Charge at lower tenure results into lower Total Charge. Hence, all these 3 factors viz Higher Monthly Charge, Lower tenure and Lower Total Charge are linkd to High Churn.

**11. Build a corelation of all predictors with 'Churn' **
"""

plt.figure(figsize=(20,8))
telco_data_dummies.corr()['Churn'].sort_values(ascending = False).plot(kind='bar')

"""**Derived Insight: **

HIGH Churn seen in case of Month to month contracts, No online security, No Tech support, First year of subscription and Fibre Optics Internet

LOW Churn is seens in case of Long term contracts, Subscriptions without internet service and The customers engaged for 5+ years

Factors like Gender, Availability of PhoneService and # of multiple lines have alomost NO impact on Churn

This is also evident from the Heatmap below
"""

plt.figure(figsize=(12,12))
sns.heatmap(telco_data_dummies.corr(), cmap="Paired")

"""Bivariate Analysis"""

new_df1_target0=telco_data.loc[telco_data["Churn"]==0]
new_df1_target1=telco_data.loc[telco_data["Churn"]==1]

def uniplot(df,col,title,hue =None):

    sns.set_style('whitegrid')
    sns.set_context('talk')
    plt.rcParams["axes.labelsize"] = 20
    plt.rcParams['axes.titlesize'] = 22
    plt.rcParams['axes.titlepad'] = 30


    temp = pd.Series(data = hue)
    fig, ax = plt.subplots()
    width = len(df[col].unique()) + 7 + 4*len(temp.unique())
    fig.set_size_inches(width , 8)
    plt.xticks(rotation=45)
    plt.yscale('log')
    plt.title(title)
    ax = sns.countplot(data = df, x= col, order=df[col].value_counts().index,hue = hue,palette='bright')

    plt.show()

uniplot(new_df1_target1,col='Partner',title='Distribution of Gender for Churned Customers',hue='gender')

uniplot(new_df1_target0,col='Partner',title='Distribution of Gender for Non Churned Customers',hue='gender')

uniplot(new_df1_target1,col='PaymentMethod',title='Distribution of PaymentMethod for Churned Customers',hue='gender')

uniplot(new_df1_target1,col='Contract',title='Distribution of Contract for Churned Customers',hue='gender')

uniplot(new_df1_target1,col='TechSupport',title='Distribution of TechSupport for Churned Customers',hue='gender')

uniplot(new_df1_target1,col='SeniorCitizen',title='Distribution of SeniorCitizen for Churned Customers',hue='gender')

"""CONCLUSION
These are some of the quick insights from this exercise:

Electronic check medium are the highest churners
Contract Type - Monthly customers are more likely to churn because of no contract terms, as they are free to go customers.
No Online security, No Tech Support category are high churners
Non senior Citizens are high churners
Note: There could be many more such insights, so take this as an assignment and try to get more insights :)
"""

telco_data_dummies.to_csv('IBM_Client_Churn_Analysis_Staging.csv')

timestamp = datetime.now()
time_stamp = timestamp.strftime("%Y-%m-%d %H:%M")
bucket = "ibm-internship-major-staging"
S3_PREFIX = f"ibm_internship_major/staging/{time_stamp}"
file_name = "IBM_Client_Churn_Analysis_Staging"
S3_KEY = S3_PREFIX+file_name

timestamp = datetime.now()
time_stamp = timestamp.strftime("%Y-%m-%d_%H-%M")

bucket = "ibm-internship-major-staging"
S3_PREFIX = f"ibm_internship_major/staging/{time_stamp}/"
file_name = "IBM_Client_Churn_Analysis_Staging.csv"

S3_KEY = S3_PREFIX + file_name


try:
    output = BytesIO()
    telco_data_dummies.to_csv(output, index=False)
    output.seek(0)
    s3.upload_fileobj(output, bucket, S3_KEY)
    print(f"Successfully uploaded to: s3://{bucket}/{S3_KEY}")
except Exception as e:
    print(f"Failed to upload: {e}")





response = s3.list_objects_v2(Bucket=bucket, Prefix=S3_PREFIX)

found_key = None

if 'Contents' in response:
    print("Files found:\n")
    for obj in response['Contents']:
        print(obj['Key'])
        if "IBM_Client_Churn_Analysis_Staging.csv" in obj['Key']:
            found_key = obj['Key']
            print(f"\n Selected file: {found_key}")
            break
else:
    print("No files found.")

if found_key:
    data = read_from_s3(bucket, found_key)
    print("Data loaded successfully!")
else:
    print("File not found.")



timestamp = datetime.now()
time_stamp = timestamp.strftime("%Y-%m-%d_%H-%M")

bucket = "ibm-internship-major-destination"
S3_PREFIX = f"ibm_internship_major/destination/{time_stamp}/"
file_name = "IBM_Client_Churn_Analysis_Destination.csv"

S3_KEY = S3_PREFIX + file_name



try:
    output = BytesIO()
    data.to_csv(output, index=False)
    output.seek(0)
    s3.upload_fileobj(output, bucket, S3_KEY)
    print(f"Successfully uploaded to: s3://{bucket}/{S3_KEY}")
except Exception as e:
    print(f"Failed to upload: {e}")